export const BASE_URL = 'https://api.daechwita.nomoredomains.rocks';

export const SHORT_MOVIES_LENGTH = 40;

export const LARGE_SCREEN_BREAKPOINT = 1280;
export const MEDIUM_SCREEN_BREAKPOINT = 760;

export const LARGE_SCREEN_INITIAL_MOVIES_AMOUNT = 12;
export const MEDIUM_SCREEN_INITIAL_MOVIES_AMOUNT = 8;
export const SMALL_SCREEN_INITIAL_MOVIES_AMOUNT = 5;

export const LARGE_SCREEN_ADDITION_MOVIES_AMOUNT = 3;
export const MEDIUM_SCREEN_ADDITION_MOVIES_AMOUNT = 2;
export const SMALL_SCREEN_ADDITION_MOVIES_AMOUNT = 2;